spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://rm-2ze5muw8tb37i3ig4lo.mysql.rds.aliyuncs.com:3306/bpo-code?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8 # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
    # name: code-generator
    username: root
    password: "!@#Qaz741"
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # Redis数据源
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 39.97.209.4
    password: 123123
    # Redis服务器连接端口
    port: 8899
    timeout: 6000
    # Redis服务器连接密码（默认为空）  如果为空则需在ShiroConfig文件中不设置redis密码，否则异常
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

management:
  security:
    enabled: false

zhengqing:
    swagger:
        title: 代码生成器接口文档
        description: 代码生成器接口文档
        version: 1.0.0
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
    #上传相关
    upload:
        staticDomain: xxx
